- server/db/nerdAssets.js
> Feature: NerdAsset assets for seed.js

- server/db/models/index.js
- server/db/models/product.js
> add: correct associations in db

- script/seed.js
> Feature: Seed file -- imports nerdAssets and creates 2 products

- package-lock.json
- script/seed.js
- server/db/models/itemsInCart.js
- server/db/nerdAssets.js
Added some dummy data to the seed file.
running createdb grace-shopper and npm run seed will successfully seed
> add: dummy data for db

- client/components/AllProducts.js
- client/components/index.js
- client/routes.js
> feature: AllProducts Route created

- client/components/AllProducts.js
- client/components/navbar.js
- public/index.html
> feat: added links to navbar

- client/store/cartItems.js
> Cart Redux

- client/components/AllProducts.js
- client/components/Cart.js
- client/store/cartItems.js
> Feature: edit cart, change qty

- package-lock.json
- package.json
- server/api/products.spec.js
- server/api/users.spec.js
- server/db/models/cart.spec.js
- server/db/models/product.spec.js
> Backend routes

- client/components/AllProducts.js
- client/components/SingleProduct.js
- client/components/navbar.js
- client/store/cartItems.js
- public/style.css
> Feature: styling updated

- client/components/SingleProduct.js
- client/routes.js
- server/db/models/product.js
> single page view fixed

- client/components/SingleProduct.js
- client/store/index.js
- client/store/localStorage.js
- package-lock.json
- package.json
- public/style.css
> feature: Local Storage persist and Single Product view updated

- client/components/EditProduct.js
- client/store/products.js
- client/store/singleProduct.js
- server/api/products.js
- server/db/models/product.js
Admin now able to delete products on admin all products page.
Admin has full functionality with products.
> feat: admin able to delete product

- client/store/cartItems.js
> Fix: Quantity in addToCart

- client/components/Cart.js
- client/store/cartItems.js
> Remove item from cart

- client/components/AllProducts.js
- client/components/SingleProduct.js
- client/store/cartItems.js
> Feature: adding to cart reviews cart first

- client/store/cartItems.js
> Fix: comment out Axios call to POST to CartItems

- client/store/activeCart.js
- client/store/cartItems.js
- client/store/index.js
- server/api/carts.js
- server/api/index.js
Very basic active cart. If there is no active cart on app load, new one will be created.
> feat: activeCart in store linked to carts db

- client/components/AllProducts.js
- client/store/cartItems.js
- server/api/cartItems.js
- server/db/models/cartItems.js
> Feature: Cart Thunk...work in progres

- server/api/products.js
- server/api/users.js
> Feat: Admin Protected Routes

- client/components/AllProducts.js
- client/components/auth-form.js
- client/routes.js
- client/store/activeCart.js
- client/store/cartItems.js
- client/store/index.js
- client/store/user.js
- server/api/cartItems.js
- server/api/carts.js
> feat: linked cart in db to logged in user

- client/components/Cart.js
- client/store/cartItems.js
- server/api/cartItems.js
> feat: cart edit

- client/store/cartItems.js
- server/api/cartItems.js
> Feat: Backend Delete Route

- client/store/cartItems.js
- server/api/cartItems.js
> fix: removing cartItem for logged in user

- client/components/AdminDashboard.js
- client/components/AdminProducts.js
- client/components/AdminUsers.js
- client/components/AllProducts.js
- public/style.css
> Feature: css styling to admin views.

- client/components/AllProducts.js
- client/components/Cart.js
- client/store/cartItems.js
- server/api/cartItems.js
- server/db/models/cartItems.js
> Fix: Updated CartAPIs, addItemToCart Thunk and cleaned up logging

- client/components/Cart.js
- client/store/cartItems.js
- server/api/cartItems.js
> Edits for riley

- server/api/cartItems.js
- server/api/checkUser.js
> Feature: protection added (needs testing) to protect cart function

- client/routes.js
- client/store/activeCart.js
- client/store/cartItems.js
- client/store/user.js
- server/api/cartItems.js
> fix: cart items linked to logged in user

- server/api/cartItems.js
- server/api/checkUser.js
- server/db/models/cartItems.js
> fix: checkUser

- client/components/Cart.js
- public/style.css
- server/api/users.js
> Cart css added

- client/components/Cart.js
- client/store/cartItems.js
- client/store/index.js
- client/store/user.js
- server/api/checkUser.js
> Storage fix

- client/components/Cart.js
- client/components/cartIcon.js
- client/components/navbar.js
- client/store/cartItems.js
- public/style.css
- server/api/cartItems.js
- server/api/carts.js
- server/api/products.js
- server/api/users.js
> Chuck ranga checkout

- client/components/Cart.js
- public/style.css
> Feature: cart totals, and subtotals

- client/components/Cart.js
- client/store/cartItems.js
- public/style.css
- server/api/cartItems.js
- server/api/carts.js
> Adam chuck ranga checkout

- client/components/AdminProducts.js
- client/store/cartItems.js
- server/api/cartItems.js
- server/api/carts.js
> fix: adding items, feat: checkout alert
